name: "grey_page_media_player"

version: 0.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  npxl_video:
    git:
      url: https://github.com/oreal-solutions/npxl-video.git

dev_dependencies:
  test: any
